// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9TjzmuxHZ6-M0InM6H2Eo32Iz4icwk0g',
    appId: '1:1003432486441:web:299d77083d1bd0cc299e38',
    messagingSenderId: '1003432486441',
    projectId: 'flutterquiz-56d72',
    authDomain: 'flutterquiz-56d72.firebaseapp.com',
    databaseURL: 'https://flutterquiz-56d72-default-rtdb.firebaseio.com',
    storageBucket: 'flutterquiz-56d72.appspot.com',
    measurementId: 'G-XR1NH6CDB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAeOVBoutQo7jHoqdDgS6TFMe1Clu5G9w',
    appId: '1:1003432486441:android:13385ab9d54da06f299e38',
    messagingSenderId: '1003432486441',
    projectId: 'flutterquiz-56d72',
    databaseURL: 'https://flutterquiz-56d72-default-rtdb.firebaseio.com',
    storageBucket: 'flutterquiz-56d72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKKUrP3R5N3InzwyHghGRBkAivYr8UCo8',
    appId: '1:1003432486441:ios:2570ef6718e818fa299e38',
    messagingSenderId: '1003432486441',
    projectId: 'flutterquiz-56d72',
    databaseURL: 'https://flutterquiz-56d72-default-rtdb.firebaseio.com',
    storageBucket: 'flutterquiz-56d72.appspot.com',
    iosClientId: '1003432486441-688r48j2nh6bupi4lji53e68jbu5k193.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompleteGuide.testing',
  );
}
